# config.yaml 

# --- Paramètres Généraux ---

experiment_name: "test0"
device: "cuda"
seed: 42
debug: False

# --- Chemins ---
paths:
  #base_dir: "/lustre/fsn1/projects/rech/tgu/uxc45lm/pclean_freesurfer"
  base_dir: "/home/st283990/pclean_freesurfer"
 

  output_dir: "/neurospin/dico/stounsi/Runs/2025_stounsi_slabeling/output/test_transfer/${experiment_name}"
  cache_dir: "/neurospin/dico/stounsi/Runs/2025_stounsi_slabeling/models/surfify_cache"

cross_validation:
  k_folds: 4      # Nombre de folds (ex: 4 pour ~12-16 sujets par fold)
  test_ratio: 0.35     #  sujets gardés pour le Test Set final (figé)
  seed: 4            # Seed critique pour que le Test Set ne change jamais
# --- Données (Configuration du Dataset) ---
data:
  hemisphere: "rh"
  ico_order: 6
  nb_vertex_thousands: 40 #(10k for ico5 , 40k for ico6 ,  168k for ico7)
  batch_size: 10
  num_classes: 66
  in_channels: 2
  #sulci_to_unknown: -1
  sulci_to_unknown : [2]

  split_ratio: 0.5
  zhao_neigh: False  
  use_lines: False
  num_workers: 1


  inputs:


 

  # Le fichier cible (ground truth)
  target: 


  # --- Augmentations ---
  augmentations:
    # Probabilités globales
    prob_geometric: 0.8   # Rotation
    prob_intensity: 0.8   # Bruit/Scale

    # Paramètres
    noise_sigma: 0.1    # Ecart-type du bruit gaussien
    scale_limit: 0.1      # +/- 10% de scaling (0.9 à 1.1)
    rotate_angle_std: 0.0 # En radians (~30 deg). Si None, utilise pi/6 par défaut

# --- Modèle ---

# model:
#   name: "SphericalUNet"
#   params:
#     depth: 5
#     start_filts: 16
#     conv_mode: "DiNe"
#     dine_size: 1
#     up_mode: "interp"
#     standard_ico: True

# --- Modèle ---
# model:
#   name: "SPHARM_Net"

#   params:
#    
#     C: 64
#     L: 80
#     D: 4

# model : 
#   name: Spherical2DCNN
#   params: 
#     in_channel: 3



model:
  name: "PretrainedUNet" 
  params:

    pretrained_ckpt: 

    freeze_encoder: False
    use_3_channels: True
    dropout: 0.25
    use_skip_adapter: False
    
    # Paramètres du décodeur (doivent être cohérents avec l'encodeur)


    backbone_params:
      start_channels: 32
      num_blocks: 5
      pooling_type: "max"
      conv_mode: "DiNe"
    
      global_pooling: "flatten" 
      standard_ico: True
  
# model:
#   name: "SphericalDinoV2"
#   params:
#     img_size: 910         
#     dino_version: "dinov2_vitb14"  
#                                    
#     unfreeze_blocks: 2

# model:
#   name: "SphericalDinoV3Linear"
#   params:
#     img_size: 528         
#     dino_version: "facebook/dinov3-vits16-pretrain-lvd1689m" 
#                                    
#     unfreeze_blocks: 2

# model:
#   name: "SphericalDinoV3"
#   params:
#     img_size: 528 # Multiple parfait de 16x3
#     #ID Hugging Face officiel
#     # dino_version: "facebook/dinov3-vits16-pretrain-lvd1689m" 
#
#     dino_version: "facebook/dinov3-vitb16-pretrain-lvd1689m"

training:
  lr: 1e-4
  encoder_lr: 1e-5
  weight_decay: 1e-3
  epochs: 500
  post_train: True 

  early_stopping_patience: 8 
  early_stopping_min_delta: 0.01
  
  #
  monitor_metric: "dice"  
  monitor_mode: "max"   

  save_freq: 80
  log_freq: 1
  val_freq: 20


# --- Loss ---
loss:
  type: "dice_ce"
  dice_weight: 1.0
  ce_weight: 1.0
  ignore_index: 0

  # weight: -1
  
  
  weight: [1.74596759e-02 4.02266651e+00 9.89880194e+00 2.65408540e+01
 2.02030889e+00 3.70432671e+00 2.99753014e+01 5.75397021e+00
 1.53775834e+01 2.29608868e+00 1.66393647e+00 2.75761896e+00
 4.45003952e+00 1.13104467e+01 8.18391608e+00 7.25581025e+00
 3.04085731e+00 5.04837557e+00 4.17418022e+00 9.87321177e+00
 3.67498822e+01 8.04337794e+00 5.53193213e+00 1.23515443e+01
 1.41827531e+01 4.27223706e+00 3.07685085e+00 6.58679842e+00
 2.06423960e+00 5.01776286e+00 3.21256304e+00 6.33575536e+00
 1.26247900e+01 7.36123716e+00 4.29119195e+00 8.76779331e+00
 5.66856724e+00 1.91350556e+01 1.15463002e+01 6.13077887e+00
 1.58168496e+01 1.88302494e+01 6.57661925e+00 1.04627194e+01
 9.89288475e+00 1.17605427e+01 9.69645679e+00 8.46579929e+00
 2.43127618e+00 1.07729837e+01 2.86767949e+01 2.51940583e+01
 1.08364695e+01 1.39909142e+01 1.01255794e+01 3.70248509e+00
 1.73335590e+01 1.92016595e+01 1.40728716e+01 2.00063496e+01
 2.21055614e+01 2.84848485e+01 1.36087047e+01 1.40768616e+01
 2.77472565e+01 3.61961781e+01]